baseURL = "https://linfn.dev/"
languageCode = "zh-cn" # http://www.rssboard.org/rss-language-codes
title = "linfn's Blog"
theme = "hermit"

rssLimit = 10
# This message is only used by the RSS template.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."

hasCJKLanguage = true
enableEmoji = true

# syntax highlighting
pygmentsCodefences  = true
pygmentsUseClasses  = true

googleAnalytics = "UA-154217073-1"

[author]
  name = "linfn"

# Hugo 0.60 开始使用 goldmark 作为默认 Markdown 引擎, 
# 这里仍使用 Blackfriday 是因为需要 hrefTargetBlank 特性
[markup]
  defaultMarkdownHandler = "Blackfriday"
  [markup.blackfriday]
    hrefTargetBlank = true
    # noreferrerLinks = true
    # nofollowLinks = true

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "将所学, 所思, 简洁清晰地表述出来."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/linfn"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
